---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  tasks:
    - name: get key for skylight
      command: "ls -ltr  /var/lib/awx/projects/_16__skylight_provision/workshops"
      register: output

    - name: print files
      debug: 
        var: "{{ output.stdout }}"