---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  vars:
    workshop_prefix: telstra
  tasks:

    - name: print file
      command: "cat /var/lib/awx/projects/_16__skylight_provision/workshops/{{ workshop_prefix }}/*private.pem"
      register: key

